# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HR <- function() {
    .Call('_rGBAT24B_HR', PACKAGE = 'rGBAT24B')
}

GBAT_1 <- function(x, id_col, add_col, third_col, third_col_type = "boro_code", unit_col = "") {
    .Call('_rGBAT24B_GBAT_1', PACKAGE = 'rGBAT24B', x, id_col, add_col, third_col, third_col_type, unit_col)
}

GBAT_2 <- function(x, id_col, hse_num_col, add_col, third_col, third_col_type = "boro_code", unit_col = "") {
    .Call('_rGBAT24B_GBAT_2', PACKAGE = 'rGBAT24B', x, id_col, hse_num_col, add_col, third_col, third_col_type, unit_col)
}

GBAT_3 <- function(x, id_col, street_name1, street_name2, boro_code1, boro_code2 = "", compass_dir = "") {
    .Call('_rGBAT24B_GBAT_3', PACKAGE = 'rGBAT24B', x, id_col, street_name1, street_name2, boro_code1, boro_code2, compass_dir)
}

GBAT_BL <- function(x, id_col, bbl_col) {
    .Call('_rGBAT24B_GBAT_BL', PACKAGE = 'rGBAT24B', x, id_col, bbl_col)
}

GBAT_BN <- function(x, id_col, bin_col) {
    .Call('_rGBAT24B_GBAT_BN', PACKAGE = 'rGBAT24B', x, id_col, bin_col)
}

