#' The \code{GBAT.process_BBL} function allows the user to select a release or version of DCP's Geosupport to geocode a data frame containing a column of BBL (borough-block-lot) tax lot identifiers.  It aggregates duplicates, geocodes, and then merges the geocoded results back to the original data frame.  The \code{GBAT.process_BBL} function utilizes Geosupport function BL.
#'
#' @details Geosupport can be downloaded from \href{https://www1.nyc.gov/site/planning/data-maps/open-data.page#geocoding_application}{DCP BYTES of the BIG APPLE}. Excellent documentation is provide in the \href{https://nycplanning.github.io/Geosupport-UPG/}{Geosupport System User Programming Guide}. The geocoder return fields are described in \href{https://nycplanning.github.io/Geosupport-UPG/appendices/appendix13/}{Appendix 13 of the Geosupport System User Programming Guide}.
#' @title Geocode a data frame containing a column of BBL with a user selected release or version of DCP's Geosupport.
#' @name GBAT.process_BBL
#' @aliases GBAT.process_BBL
#' @export GBAT.process_BBL
#' @param in_df a data frame containing a column of BBL.  Required.
#' @param bbl_col_name the name of the column containing the input BBL as string.  Required.
#' @param source_cols vector of column names from the input data frame to be returned with geocoder results.  Required.
#' @param geocode_fields vector of field names generated by the geocoder to be returned with geocoder results.  Required.
#' @param return_type option to exclude address which failed to geocode from output as string.  Optional.
#' @param GBAT_name the release or version of DCP's Geosupport geocoding software as string.  Required.
#' @usage GBAT.process_BBL(in_df, bbl_col_name, 
#'     source_cols, geocode_fields, return_type = "all", 
#'     GBAT_name)
#' @return A data frame containing the columns specified in \code{source_cols} plus the geocoder return fields specified in \code{geocode_fields}.
#' @examples #create a data frame of BBL
#' in_bbl <- 1001990021
#' BBL <- as.character((in_bbl-10):(in_bbl+10))
#' u_id <- 1:length(BBL)
#' df = data.frame(u_id, BBL)
#'
#' #specify columns from input data frame to retain
#' source_cols <- c('u_id')
#'
#' #specify geocoder return fields
#' geocode_fields <- c("FBL.bbl", "FBL.RPAD_lucc", "FBL.coord1", "FBL.coord2", 
#'     "FBL.latitude", "FBL.longitude", "FBL.nbr_blds", "FBL.addr_range_1ax1.bin", 
#'     "FBL.addr_range_1ax2.bin","FBL.addr_range_1ax3.bin")
#'
#' #geocode data frame by BBL
#' df_gc <- GBAT.process_BBL(in_df=df, bbl_col_name="BBL", 
#'     source_cols=source_cols, geocode_fields=geocode_fields, 
#'     return_type="all", GBAT_name="20C")


GBAT.process_BBL <- function(in_df, bbl_col_name, source_cols, geocode_fields, return_type = "all", GBAT_name) { 

	return(parallel.GBAT.process_BBL(1, in_df, bbl_col_name, source_cols, geocode_fields, return_type, GBAT_name))
	
}